### ISSUE TITLE
Feature request: middle click in cotext menu to search without closing menu

### ISSUE THREAD

**Issue by reembar** [ssborbis/ContextSearch-web-ext#102]
This is a feature request:
I use Firefox with ContextSearch web-ext only in the context menu.
I would love an option to middle click an engine to open it in a new background tab while keeping the context menu open, so I can search in several engines at once without opening the menu again.
Thank you for your great extension!

**Comment by ssborbis** [comment]
Unfortunately, right now there is no way to listen for anything but a left-click and modifier keys like ALT and SHIFT in the context menu on Firefox, . The Chrome version doesn't even support modifier keys :(

The Quick Menu can do a lot more than the context menu because it essentially runs as a web page, so you can get right-middle-left click events, but the API for the menus in the browser UI are limited. If you want middle-click options, you'll have to use the Quick Menu
