### ISSUE TITLE
toolbar: ignore search suggestions using keyboard

### ISSUE THREAD

**Issue by githubeing** [ssborbis/ContextSearch-web-ext#160]
the use case is:

1. click extension button on browser extensions bar
2. the toolbar opens
3. the search input field is focused
4. type in the search query from keyboard
5. the search suggestions appear
6. don't use mouse from this moment
7. press `tab` to move focus to search engines list
8. select search engine from using arrow keys
9. press `enter` to open search results

the problem is that on step 7, when you press `tab`, the first search suggestion replaces your search query, therefore the only way to search exactly what you want without completely disabling search suggestions is to use your mouse after you've typed your query in.

could you please fix that?

**Comment by githubeing** [comment]
P.S.: Chromium Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on Ubuntu 18.10 (64-bit)

**Comment by ssborbis** [comment]
If you're sideloading, you can try the latest push

Behavior more closely matches the FF built-in search bar
`{tab}` moves from search bar to search tiles
`{down arrow}` moves from search bar to suggestions

There are also a few tweaks of note:

* Keyboard navigation moves tiles into view if offscreen
* useless scrollbars removed from the toolbar in chrome
* better? toolbar width handling when opening suggestions ( this one is a pain due to the differences in window resizing by FF and chrome )

**Comment by githubeing** [comment]
i've installed the extension via chrome store, didn't sideload
