### ISSUE TITLE
Keyboard shortcut to open toolbar popup

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#237]
Would be very handy to have a keyboard shortcut to summon the toolbar menu, like already possible with the sidebar popup.

**Comment by ssborbis** [comment]
It's possible, but the shortcut can't be set by users. I'd have to choose a key combo. I didn't want to conflict with other addons, so I left this option off.

**Comment by sojusnik** [comment]
That's strange! Other add-ons like [this](https://addons.mozilla.org/de/firefox/addon/search-site-we/) do allow to set your own keyboard shortcut to open a pop-up from the toolbar. So where does the limitation lie?

**Comment by ssborbis** [comment]
The way they're doing it is only available to FF.

**Comment by ssborbis** [comment]
Oh, and this addon does do site search FYI. Dunno if you've ever used that tile.

**Comment by sojusnik** [comment]
> The way they're doing it is only available to FF.

I assume that implementing a FF only shortcut would be too time-consuming?

> Oh, and this addon does do site search FYI. Dunno if you've ever used that tile.

What do you mean by "site search"? The add-on I've linked allows to conveniently search a site through a search engine like Google, either the entire or the sub-domain.

**Comment by ssborbis** [comment]
> I assume that implementing a FF only shortcut would be too time-consuming?

Actually, it's pretty easy to do. I meant the reason I never implemented it was because it wasn't available to chrome, and I try to keep things working cross-browser. When I get some time I'll take a look.

> What do you mean by "site search"? The add-on I've linked allows to conveniently search a site through a search engine like Google, either the entire or the sub-domain.

You can set up a search engine to use domain / subdomain info as a variable in the search template. This causes the search engine tile to act like a folder and display a list of domains / subdomains to restrict your search to. CS comes with google site search already set up. I think the other engines use a similar if not identical template for their site search query, so all you'd need to do to set up Bing is copy the engine and change google.com to bing.com, etc

![sitesearch](https://user-images.githubusercontent.com/24310997/74484109-9c658980-4e7d-11ea-997c-1b4daf4232ad.gif)

![sitesearch](https://user-images.githubusercontent.com/24310997/74484171-b1421d00-4e7d-11ea-822b-38b11913c8a0.png)

**Comment by ssborbis** [comment]
You can set a hotkey to open the toolbar menu using about:addons -> Settings Icon -> Manage Extension Shortcuts in the latest push

**Comment by sojusnik** [comment]
A small observation: if the toolbar popup is opened via the new keyboard shortcut, then the search field sometimes isn't focused. So if I use the keyboard shortcut 10 times in a row, with a pause of one second in between, then the focus isn't there in three or four cases.

Happens on Ubuntu 20.04 with Firefox 80.0.1.

As always, a huge thanks for maintaining this wonderful extension!

**Comment by ssborbis** [comment]
I'll test ubuntu later, but I haven't seen that bug in a couple dozen tries on win10 FF80.

What's your shortcut key? What happens if you change it to something else?

**Comment by sojusnik** [comment]
It's Ctrl + Shift + L.

Even if I change it to another shortcut, this bug remains.

**Comment by ssborbis** [comment]
I think I got it to trigger on one in maybe 100 tries on ubuntu. I'll keep an eye out, but unless I can get a more consistent bug, I can't do much. The focus code is pretty straight-forward so there's not much to check.

**Comment by ssborbis** [comment]
@sojusnik if this is still occurring, I'll reopen
