### ISSUE TITLE
edit SearchEngine names

### ISSUE THREAD

**Issue by Nihlo** [ssborbis/ContextSearch-web-ext#24]
Hey,
thanks for the addon, love it.
Small suggestion:
would be cool if you could edit the searchengine name in the list. Got lots of old ones with similar names.

**Comment by ssborbis** [comment]
If I'm remembering correctly, I left off the ability to edit names due to how some of the logic works when importing seach.json.mozlz4 files. If you have a search engine named "Google" in your search.json.mozlz4 file and you rename it in the custom manager to "Google Custom", when you re-import your search.json.mozlz4 file (or if done by using Automatic Import via the native app), the add-on will treat the engines as two distinct search engines and you'll end up with both "Google" and "Google Custom" in your search engine manager. The addon looks for unique names in the search.json.mozlz4 file and imports those that don't exist into the custom manager and does not import names that do to prevent overwriting custom settings. If Firefox used a unique identifier for it's one-click search engines I could allow users to edit the names, but Firefox uses the search engine names as an index, so I'm kinda forced to do the same.

**Comment by ssborbis** [comment]
If you don't do much re-importing or don't mind have a duplicate search engine in your custom manager you'll have to hide, you can rename search engines from within your %profile%\browser-extension-data\{5dd73bb9-e728-4d1e-990b-c77d8e03670f}\storage.js" file. Search engine names are kept in the "title": keys

**Comment by ssborbis** [comment]
I added the ability to change names from the edit form in the search engines manager. Be aware, this only changes the names in ContextSearch, not the names stored in Firefox's search.json.mozlz4 file. Because if this, I prompt the user with a warning of potential issues like the same engine reappearing with the original name when importing.
