### ISSUE TITLE
context find

### ISSUE THREAD

**Issue by seekr9** [ssborbis/ContextSearch-web-ext#245]
Cannot open find bar from context menu with text selection entered as search term.

(sorry, couldn't find a feedback or feature request link anywhere for this awesome extension.)

**Comment by ssborbis** [comment]
Can you elaborate? I'm not sure I follow.

You can't open the default FF or Chrome Find bar using ( Ctrl + F ) if your current selection or focus is on the search bar of the quick menu?

**Comment by seekr9** [comment]
First,  ThanQ for this great extension.

This may be more of a feature request than a bug report. I would like to be able to have the FF Find Bar as an option listed in ContextSearch menu, along with my other search options. So that I can:
select text on a webpage, and then click "Find" in the ContextSearch menu, and then the Find Bar opens and the text that I have selected is already entered into the Find Bar's search box. 

or (perhaps even better)
ANY search term I run via ContextSearch through any search engine also opens the FF Find Bar and the term that I have searched for is already entered into the Find Bar's search box.

**Comment by ssborbis** [comment]
I'll look into adding the Find permission and add a tool / engine.

For the time being, you can achieve roughly the same result using a bookmarklet.

1. Open Bookmarks menu
2. Right-click somewhere in the menu and choose `New Bookmark`
3. Name it whatever you want and paste this for the location: `javascript:browser.runtime.sendMessage(Object.assign({action:"mark", searchTerms: CS_searchTerms}, userOptions.highLight.findBar.markOptions));` and click 'Add'
4. Open CS options -> Search Engines
5. Right-click where you want the new button to be in your list and choose `Add Bookmarklet` from the custom context menu that pops up.
6. The new bookmark you made should be listed by name. Click it to add that bookmarklet to your search engines menu. You can add a custom icon if you want.

The new button in your menu should bring up the CS findbar. You can customize what happens when you use it @ CS options -> Highlight

**Comment by ssborbis** [comment]
Looks like there's no way to trigger the FF built-in Find bar to open programmatically. You're stuck with the one included in this addon if you want that functionality.

**Comment by seekr9** [comment]
> That option is already available, using the CS findbar, albeit. Look into the CS options -> Highlight menu, specifically Highlight -> Search Results -> Show Find bar when highlighting

Ha! I discovered that a few days ago! Nice work. 
I'll try the bookmarklet option soon. You Rock. Thank you for your help.

**Comment by seekr9** [comment]
Just tried the bookmarklet and it works brilliantly. Thanx again.

**Comment by ssborbis** [comment]
new release v1.20.1 going up now with 'Find in page' tool added. Essentially the same code as the bookmarklet, but available in the CS tools bar

**Comment by seekr9** [comment]
just found this email. The search in page feature is awesome. Thank you.
