### ISSUE TITLE
Folder disappeared

### ISSUE THREAD

**Issue by molkes** [ssborbis/ContextSearch-web-ext#253]
Option "note: top-tier folders only" is only valid for the first-level folder. For folders of other levels, the folder disappears after enabling option "note: top-tier folders only".

**Comment by ssborbis** [comment]
That's what the note means. It won't work on folders that aren't in the root folder

**Comment by ssborbis** [comment]
The option should be called "Group layout". Are you seeing that text or a translation of it?

**Comment by molkes** [comment]
Well, I didn't notice "Group layout". Can you make the option "Group layout" take effect on subfolders?

**Comment by ssborbis** [comment]
I disabled on subfolders because there are issues with drag & drop within the menus to / from nested groups. If you want to do some testing, I can enable it. Or you can edit the source yourself. It's line 1355 of tilemenu.js 

change
`if ( node.groupFolder && !node.parent.parent)`
to
`if ( node.groupFolder)`

I think that's all it takes

**Comment by molkes** [comment]
Thanks.
