### ISSUE TITLE
activate menu entry when releasing mouse button after (quick) menu started by "hold"

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#26]
if the quick menu is started by "hold", it is much faster to select the menu entry on release of the button instead of releasing and clicking again.
I would suggest a setting for this, because not all people seem to expect this and some my be unable to execute this.

**Comment by ssborbis** [comment]
Shouldn't be difficult to implement. I have code now that prevents it from happening accidentally.

**Comment by ssborbis** [comment]
If speed is what you're after, I find using Open on Right Click to be faster than Hold due to the 250ms wait on the hold. I have noticed some unwanted behavior in some desktop environments though where the context menu is opened on mousedown vs click (whatever ubuntu 16 was using is where I saw it happen)

**Comment by hg42** [comment]
on Linux Firefox (59) I often get context menu + quick menu together, that's why I use hold right mouse button, which works usually.

Speed wasn't exactly the correct word, it's more like "less actions" or "better flow".

Action on release is dangerous for a short click, because the menu may be openend under the mouse because it is kept on-screen.
I don't see a problem for "long hold".

**Comment by ssborbis** [comment]
I get ya. I'll have something in the next release. I'm working on setting up the Options now.  

The context menu + quickmenu behavior you described is what I've experienced in Linux as well. It's either baked into the distro desktop environments that the context menu should open on mousedown vs mouseup like in windows, or some consequence of my using a virtual machine. The code for the Open on Right Click is written for the windows behavior only and gets a bit weird in some distros.

**Comment by hg42** [comment]
that's awesome...

In my last tests, the "hold" method works all the time. It seems I only get the additional context menu when the mouse button bounces, probably caused by sloppy clicking.
With "hold" (right button) the context menu does not open.

I first thought, the "click" method (with right button) would always give me the context menu and the quick menu together. But then after some tries this changed and it worked, after some time it didn't work again. So I tried harder to find a rule.

This seems to be strictly based on the timing of the right click.
* if the click is definitely short, I always get the quick menu
* if the click is very long (or I hold the button), I get the context menu alone
* then there is some slow click timing in between where I get both menus, usually the context menu first and then the quick menu. This is not easy to reproduce.

btw. the context menu allows hold and release on an entry. This is usually working well, but there are occasions where the menu is opened under the mouse (when the mouse is near the edge and the menu cannot be displayed at the usual position). Then you can start an action unintentionally if you are not aware of this behavior.

The solution is to never display the menu under the mouse pointer. So it must switch to the other side of the mouse instead of simply limiting the position to the on-screen area.

**Comment by ssborbis** [comment]
I may be using a timeout so close to what firefox / distro is using to trigger the context menu (250ms) that the behavior is inconsistent as to which action happens first. I'll do some more testing with positioning the quickmenu and click variations / timing and see if I can get better behavior on 'nix. 

On a related note, about a month ago I started getting really weird behavior from right-click when doing some debugging and thought I messed up something in my code. It turned out the switch for the button was failing causing some signal bounce. I ended up replacing the PCB mounted switch for my right button.

**Comment by hg42** [comment]
I'm not familiar with Firefox message handling, but eventually you could change the mouse event given to the next handler?

The left mouse button has a similar problem. If I select text and click and hold on the selection I start dragging the text in parallel to the quick menu (when also moving the mouse). This can result in unexpected behavior, too. I think that was a main reason, why I use the right button (apart from being more natural, because quick menu is only another context menu).

**Comment by hg42** [comment]
I get some history depended behavior.
This affected my former tests and probably some of my conclusions.

E.g. if I use "click" and right button, this usually works.
I can short click several times and always get the quick menu as expected.
Then, on a long click I get nothing.
All following long clicks correctly open the context menu.
Changing to a short click opens the quick menu and context menu in parallel.
Following short clicks work and only open the quick menu.

I get similar behavior with "Hold" and right button.
It always works except when invoking the "other" menu.

However, "Hold" and left button works all the time (quick menu or deselecting the text)
May be because no second popup menu is involved?

So I think there must be some kind of history...(may be an uninitialized variable?).

**Comment by ssborbis** [comment]
> If I select text and click and hold on the selection I start dragging the text in parallel to the quick menu (when also moving the mouse). This can result in unexpected behavior, too. I think that was a main reason, why I use the right button (apart from being more natural, because quick menu is only another context menu).
I have to click on the selection, because otherwise the selection is cleared. This is also an advantage of the right button, which doesn't clear the selection.

I have code that should prevent that behavior. I'm not sure how much I tested on linux though. I'll check again.

>So I think there must be some kind of history...(may be an uninitialized variable?).

I think I know what's going on. The way the logic is set up now for HOLD is:

1) wait for mousedown > 250ms
2) add event listener for next contextmenu event and suppress once
3) open quickmenu on mouseup

In windows this is the correct order. The contextmenu event doesn't fire until mouseup so I can suppress it during the hold. On linux, the event listener is queued until the next mousedown event triggers the context menu. So the first time you use hold, you get the context menu immediately. The next time, it's suppressed once.

**Comment by hg42** [comment]
yes, I think this explains what's going on.

**Comment by ssborbis** [comment]
Looks like I'm not the only dev seeing bad behavior on linux. The moz devs added this variable to about:config

`ui.context_menus.after_mouseup`

Set that to true and things should work as expected.

**Comment by hg42** [comment]
Oh, I missed your last comment...
Thanks for the tip, this works well on my laptop.
I have to check it on the PC later.

**Comment by ssborbis** [comment]
Search on mouseup added to v1.4.1

**Comment by hg42** [comment]
you're awesome...

The new feature works very well in combination with `ui.context_menus.after_mouseup`.

This made my day just before going to sleep.
Thanks.
