### ISSUE TITLE
Dark theme display problem in Chromium Edge 86, so probably upcoming in Chrome too

### ISSUE THREAD

**Issue by DavidBE-UK** [ssborbis/ContextSearch-web-ext#272]
I have the extension installed in Firefox (my main browser), and also Google Chrome and Chrome Beta, and the Chrome version of the extension also in Microsoft's Chromium Edge, Dev and Canary, same configuration in all.

It's been working very well in all, and I consider it an indispensable extension, for which much thanks, but a problem has appeared in Edge Dev and Canary once they moved to Chromium 86. I know you haven't put the extension into the Microsoft Edge store so maybe don't support use in Edge as such, but as Chromium Edge is based on Chromium like Google Chrome and can install extensions from the Google Chrome store with the extensions working in Edge just like in Chrome, I suspect the same issue will appear in Google Chrome when it reaches 86 too (Chrome Beta is currently 85 so I can't confirm this, but the problem did not exist in Edge Dev or Canary when they were based on Chromium 85, only appearing when they moved to 86).

The issue is simply that in dark theme the tool icons (copy, open link, close menu etc.) don't change to the lighter colour as they do in Chrome/Edge 85 and earlier. But the background colour does change as expected, leaving the tool icons almost invisible.

**Comment by ssborbis** [comment]
Thanks for the heads up. I tend to only check the FF dev builds, but I'll grab the latest Chrome and see what's going on. The code to set the tool colors is a bit convoluted, relying on canvas and masks, so that's the most likely culprit. I've been converting all my tool icons from png to svg over the last couple weeks, so when that's done I'll clean up color code. 

I'll reply here when I having something worth testing.

**Comment by ssborbis** [comment]
There's an update in the repo that seems to fix this issue and others in the latest chrome dev build.
