### ISSUE TITLE
Bug: Unable to open the FORM PATH by entering the key word of the search engine in the address bar in Firefox 83.0

### ISSUE THREAD

**Issue by jed84** [ssborbis/ContextSearch-web-ext#297]
**GIVEN** I am using Firefox 83.0
**AND** I set a FORM PATH for the specific search engine
**AND** I set a keyword to trigger the search engine in the Firefox settings
**WHEN** I enter a keyword of the search engine in the address bar
**THEN** I am no longer taken to the FORM PATH that has been previously set.

-----

Notes:
This worked correctly in Firefox 82.0 and below, but the functionality got broken as Mozilla made changes in Search feature in Firefox 83.0.

-----

Steps to reproduce (example):
1. Edit YouTube search engine and set a FORM PATH that will take you to your YouTube history page (https://www.youtube.com/feed/history);
![obraz](https://user-images.githubusercontent.com/47121522/99554581-421ec980-29b7-11eb-9b48-e16f91d2a836.png)

2. Add the modified engine to Firefox;

3. Set a keyword for the new YouTube search engine in Firefox's settings (in this scenario: "y");
![obraz](https://user-images.githubusercontent.com/47121522/99554603-4a770480-29b7-11eb-8604-e70227f64563.png)

4. Type "y" in the address bar and press Enter;
![obraz](https://user-images.githubusercontent.com/47121522/99554712-68dd0000-29b7-11eb-9052-8a7821a9ae51.png)

5. BUG: in Firefox 83.0 this no longer takes you to the URL that has been previously entered in the FORM PATH (https://www.youtube.com/feed/history).

**Comment by ssborbis** [comment]
Ok, a few things.

There are two essentially independent lists of search engines in Firefox when using this addon. 

**ContextSearch engines**
These are the engines that show up in `CS options -> Search Engines` and are editable ( no FF tag )

**Firefox One-Click Search Engines**
The engines that show up in `FF Options -> Search -> One-Click Search Engines` *AND* show up in `CS options -> Search Engines` with the (FF) tag.

Editing a CS search engine only affects icons / engines in CS menus ( context menu, quick menu, etc ), **NOT** the engines that show up using keywords or engines in the Firefox search bar. The engines listed in `FF options -> Search -> One-Click Search Engines` are **NOT** editable through CS ( those are the ones with the FF tag ).

Pre-FF83, there were ways to copy/import an engine added through CS to the FF search engine list, both when installing a new engine using the context menu option `Add to ContextSearch` or using the `Install to Firefox One-Click Search Engines` button (green circle, white plus) in the edit form. Pre-FF83, if you made changes to a CS engine and wanted to also update the version in the Firefox list, you would need to open FF options -> Search Engines, delete the old engine, and use the ``Install to Firefox One-Click Search Engines` button to re-import the engine from CS to FF. That function in FF83 appears to be depreciated, so there's no way to go from CS engines to FF engines right now. Sucks I know.

Another user ( chrome user ) suggested adding support for the Omnibox. It would effectively function like the keywords you have been using, but instead of relying on engines installed to FF, you could use CS engine hotkeys to perform the same searches from the URL bar, albeit with an additional keyword ( something like `CS g searchforthisword` vs the simpler search you're used to `g searchforthisword`. 

If that sounds like something you'd want implemented, throw in your 2 cents @ #274

**Comment by ssborbis** [comment]
Oh, I forgot to add..

My keywords for FF engines work fine. I don't know why yours are not. I added another just to check (keyword amzfr)

My method, click url bar, type amzfr (spacebar)

![keyword](https://user-images.githubusercontent.com/24310997/99582392-ab96dc00-29a7-11eb-9ecf-7d1981853924.gif)

**Comment by ssborbis** [comment]
I need to amend what I said about FF83 and opensearch engines. The workaround I added for FF78+ seems to still be working ( you can still add engines via the Firefox search bar ). Dunno why that wasn't working yesterday.

**Comment by jed84** [comment]
Hey @ssborbis 
I meant something different in my description.

In Firefox 82 and below, by entering "y" (or any other keyword) in the address bar, without adding anything else after "y", you could open the dedicated form path. So entering just a single character worked as a shortcut to the webpage.

Entering "y" could take you to the YouTube history page etc.

Now it's completely broken.
However, after you had provided your explanation on how does it work, now I don't think that anything can be done to recert the change made by Mozilla.

**Comment by ssborbis** [comment]
Yep, that's a Mozilla thing. Maybe they switched off the old default setting and you can turn it back on from about:config somewhere?

**Comment by ssborbis** [comment]
I see this setting `browser.urlbar.suggest.history` and mine was set to FALSE` and I don't think I turned it off.

**Comment by jed84** [comment]
Changing this sadly doesn't have an impact on the current behabour.

**Comment by ssborbis** [comment]
Bummer. Like I said, I never used that feature so it's hard to tell what exactly is the correct behaviour. I'll continue to work on the omnibox, but unfortunately, it won't have the history feature you're looking for :(

**Comment by jed84** [comment]
I found a way to disable the new feature in about:config
Simply set "browser.urlbar.update2" to "false".
