### ISSUE TITLE
word greyed out / looses focus can not be copied with ctrl+c

### ISSUE THREAD

**Issue by itge13** [ssborbis/ContextSearch-web-ext#299]
word greyed out / looses focus can not be copied with ctrl+c. how can I change that? I would like to copy the marked word even with the addon popping up.

![2020-11-19_131909](https://user-images.githubusercontent.com/39725549/99665858-799a7e00-2a6a-11eb-83f0-ec35da1c6643.jpg)

**Comment by ssborbis** [comment]
I assume you've hidden the search bar in the quick menu?

You can disable the option `Set focus to search bar when the Quick Menu is opened` at the bottom of CS Options -> Quick Menu

If the option is greyed out, you'll first need to go to CS options -> Hotkeys and set the Search Engines Action to No Action. This is due to a bug :(

**Comment by itge13** [comment]
> you'll first need to go to CS options -> Hotkeys and set the Search Engines Action to No Action. This is due to a bug :(

that fixed it. thanks so much:)
