### ISSUE TITLE
Can't open Quick menu at the site

### ISSUE THREAD

**Issue by bluesxblues** [ssborbis/ContextSearch-web-ext#302]
I use Chrome and this ContextSearch-web-ext worked at other site.

but can't work at the site, can I fix it ?
https://www.komica.org/

**Comment by ssborbis** [comment]
Looks like that page uses `<FRAMESET>` in place of `<BODY>` in the html document. This addon relies on `<BODY>` to function. The only workaround I can see is to link directly to https://www.komica.org/bbsmenu.html or https://www.komica.org/mainmenu2019.html

This is the first site I've seen in a long time that uses frames. I'll look into a workaround, but for now, there isn't much you can do other than rely on the context menu option instead of the quick menu.

**Comment by bluesxblues** [comment]
Thank you,  I hope it will worked one day.

**Comment by Beexx** [comment]
Hello,
I noticed the same kind of problem on all Firefox addon pages. For instance, I can't open the Quick Menu on the following page :
https://addons.mozilla.org/fr/firefox/addon/contextsearch-web-ext/
The HTML source code contains a <body> statement, though.
It works on other pages like https://framagit.org/ariasuni/tabcenter-reborn/-/wikis/home.

**Comment by ssborbis** [comment]
@Beexx Mozilla restricts certain addon features ( namely content scripts ) on some domains by default. It's a security feature. There's a pref in about:config you can change to allow it. I don't remember what it is offhand

**Comment by Beexx** [comment]
Thanks @ssborbis, that would explain.
I've tried changing extensions.webextensions.restrictedDomains, but it didn't work. There might be another hidden pref somewhere.
Anyway, it's not that important, I'll avoid using the extension on Mozilla sites...
