### ISSUE TITLE
Feature request: Support mycroftproject.com

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#339]
I have a Feature request. 

Sometimes it is difficult to add a search engine and also get it to work. Here is one example I did add but could not get to work:   https://forvo.com   

What did help in the end: Use this site https://mycroftproject.com/ ... add forvo to the firefox search engines and then import it from firefox via the file:search.json.mozlz4 into ContextSearch. ... 

Maybe there is a way to get this done easier? ... Maybe somehow support mycroftproject?

**Comment by ssborbis** [comment]
There is a bit of mycroftproject integration already. If you right-click the search bar at forvo.com -> Add to ContextSearch ->  Advanced -> Find, it will take you to the forvo.com search results of mycroftproject.com.

 It's a bit trickier to integrate any further due to having no control over how the dev at mycroftproject chooses to generate / serve the their plugins, but I'll see what can be done.

**Comment by ThomasSeeker** [comment]
Yes, I understand. ... Hm, maybe you find a way further. ... Thank you!

**Comment by ssborbis** [comment]
I have this workaround in development. It works for the new method mycroftproject uses as well as any other site that serves an opensearch plugin

![mycroftproject](https://user-images.githubusercontent.com/24310997/118603983-3a7b8a00-b77a-11eb-96e4-8a614f7bf2f7.png)

**Comment by ThomasSeeker** [comment]
Ah, ... ! ... I'm looking forward to try this!

Thank you very much!!!

**Comment by Github-PCDesktop** [comment]
I'm sorry I messed up the #. I post another picture to clarify the suggestion and... after seeing the picture above I encountered a issue and I don't know if it is caused by some settings not selected in 'ContextSearch', a new bug or something else:

<img src="https://i.postimg.cc/d046KPqG/Image-C.png">

**Comment by ssborbis** [comment]
@Github-PCDesktop 

The latest code will prompt with the usual add engine menus if you try to add an opensearch engine like so...

![Peek 2021-06-21 21-20](https://user-images.githubusercontent.com/24310997/122852718-af406780-d2d6-11eb-9a84-24eb2fa79b3d.gif)

**Comment by Github-PCDesktop** [comment]
> 
> 
> @Github-PCDesktop
> 
> The latest code will prompt with the usual add engine menus if you try to add an opensearch engine like so...
> 

Ok, thanks. I assumed it was already there in the meantime considering that I just installed the extension. Too many search engines in these days have me a little off my game.

**Comment by ssborbis** [comment]
Been a while, but I'm going to include this feature in the next release. It adds a ContextSearch icon next to search engine links on mycroftproject.com. Click the icon to install the engine to ContextSearch.

![mycroft](https://user-images.githubusercontent.com/24310997/147843528-f224210a-9633-4f21-9ca8-46cdd25c7215.gif)

**Comment by ThomasSeeker** [comment]
Wow! ... This looks wonderful! ... Looking forward to try it out! ... :-)
Thank you very very much!

**Comment by ssborbis** [comment]
1.33 is live in AMO and chromestore

**Comment by ThomasSeeker** [comment]
Just beautiful! ... It works like a charm! 
Thank you very much! ... :-)

**Comment by ssborbis** [comment]
My pleasure. Sorry it took this long.

If you have any problems, open an new issue or re-open this one. Either way.
