### ISSUE TITLE
[FEATURE] Permanent Disable Menu "No script injection" on specific urls ex: localhost 

### ISSUE THREAD

**Issue by mustafaabobakr** [ssborbis/ContextSearch-web-ext#343]
Thank you and Love the extension ♥

### **Can you please add the ability to disable the extension per URL!**
Just like the uBlock Origin

_Thank You_

![image](https://user-images.githubusercontent.com/27288406/118357479-b0b19e00-b57a-11eb-9aad-ea9375b25629.png)

**Comment by ssborbis** [comment]
I'm not sure how uBlock Origin does it, but I have a basic setup in the works. I plan on making a development branch and putting new changes there, so I'll let you know when there's something to test in the repo.

**Comment by ssborbis** [comment]
Here's the basic function in action (GIF is a bit jumpy, but you get the idea). Gonna be a while before it makes in into a release, not because it's not ready, but because I have some unrelated but significant backend changes that need to be worked out first.

![blocklist](https://user-images.githubusercontent.com/24310997/118413155-753ece80-b663-11eb-9fb0-2f87e8da00c9.gif)

**Comment by dnknn** [comment]
@ssborbis 
 `㊀ blacklist ㊀` feature: only can `location.hostname` ❓

## **If it is easy to achieve:**
 - support `location.href` / `document.URL`
 - support `*` wildcard
 - support `RegExp`  (Just like search engine manager for RegExp ` "RegExp"`)

**Comment by ssborbis** [comment]
@dnknn 

When would you use wildcards and regex?

**Comment by dnknn** [comment]
> When would you use wildcards and regex?

For example for current url : 
```
	https://github.com/ssborbis/ContextSearch-web-ext/issues/343
```

When you need to exactly match the path of the URLs, it can come in handy at this time.

In other words:  but it does not work on a certain page/type of page on the domain.

```
	https://github.com/ssborbis/ContextSearch-web-ext/issues/*
	https://github\.com/ssborbis/ContextSearch-web-ext/issues/\d+
```
---------------------------------------------------------------------

- In other words: If only supports the `domain` match, Obviously, it cannot precisely meet the matching requirements.
> You only have 2 options:
Either it works on all pages of the domain, or it doesn't work on all pages of the domain.

I think our ContextSearch web-ext extension, Obviously, a flexible/accurate matching mode is required for this function to be meaningful.

### Because: 

In normal almost all pages, we will enable extensions by default.
But if you encounter compatibility issues with very few pages or do not want to display the `🔍` icon on a specific page, 

Obviously, only the matching method of the host can certainly not meet this matching demand.

**Comment by ssborbis** [comment]
@dnknn 

Fair enough. I'm looking into it.

**Comment by dnknn** [comment]
> edit) I mean aside from the obvious *.[google.com](http://google.com) type examples

@ssborbis  No.... What you mean is still targeting `Domain` or `Subdomain`.

I mean is for `href` (the entire URL string).

[There is no problem with this approach.](https://user-images.githubusercontent.com/10995302/118552646-ca78fe00-b791-11eb-9c27-ac2b446ca69c.png)

What I mean is that if users need to match the URL exactly, they can enter the advanced options page and fill in the exact/complete matching mode by themselves.

It shouldn't be difficult to match `location.href`, this is a native JavaScript interface.

You should understand the meaning now, right?

**Comment by ssborbis** [comment]
@dnknn 

Yeah, I've got it working (limited testing).

1. checks for hostname match
2. checks for regex match ( using url.href )
3. checks for wildcard match ( using hostname and url.href )

**Comment by dnknn** [comment]
@ssborbis  👍Good! 
Regarding the function of this module, can you add two more good ideas:

## 1. Add the comment(disable) function at the beginning of the line.
For example:
```js
https://github.com/111/xx
https://google.com/222/
```

```js
https://github.com/111/xx
!https://google.com/222/	👈// OFF/disabled 
#https://google.com/222/	👈// OFF/disabled
```
> Through the comparison of the above two examples, you should be able to roughly understand the meaning.

> Actually uBlock Origin also has this function: 
![image](https://user-images.githubusercontent.com/10995302/118558724-9dc8e480-b799-11eb-882b-2296d91a6b35.png)

　
Obviously this is useful, You can use comment lines without deleting lines, It can easilyswitch `ON/OFF`


-----

## 2. info-help 
> Now supports exact complete matching mode, 
so at the same time it is necessary: seeing 👇

![image](https://user-images.githubusercontent.com/10995302/118557564-eda6ac00-b797-11eb-8602-46cae51727a5.png)

> So that the user can know the specific situation of the function.

**Comment by ssborbis** [comment]
Ok, changes are going up at the new development branch. Be aware, there's a lot of test code on that branch, especially regarding group folders and tile menu click handlers. It's probably not suitable for normal use at the moment, but I'll look to tidy some things up and get it looking more usable in the future.

**Comment by ssborbis** [comment]
Dev branch is relatively stable now. You will need to backup your config if you plan on downgrading from the repo code.

Signed mozilla extension is in releases https://github.com/ssborbis/ContextSearch-web-ext/releases/tag/1.30a1

**Comment by ssborbis** [comment]
This feature is in the release versions now, so I'll close. If there's any problems, open a new issue.
