### ISSUE TITLE
[Feature requests] Some optional suggestions for a very good add-on

### ISSUE THREAD

**Issue by ghost** [ssborbis/ContextSearch-web-ext#347]
After a deep survey of all 'context search' add-ons I finally choose yours due a very well design and global options (thanks!). Some tips in order of personal importance (but I'm already happy even without them):

- an option to Folders to choose opening all engines in multitabs (or add a new 'Group' feature for this)
- about Mycroft Project: rather then the ability to add an engine from the site (useful off course), actually I really like the opportunity to quickly show the related engine parameters (Template and Icon URI) before install like 'Selected search' add-on
- an icon in Tools for 'Search inside site' (subdomain\entire domain)
- boxes to tick (unselect after searching) in text view for multitabs search again with icon in Tools ('multitabs search for selected engines')
-  double right click search option using default Firefox search engine (or latest used engine in ContextSearch) without using Quick Menu

**Comment by Github-PCDesktop** [comment]
Sackcloth and ashes... The extension supports the option to open multiple search engines by folder. It borders on perfection. I have to to practice...

**Comment by ssborbis** [comment]
> about Mycroft Project: rather then the ability to add an engine from the site (useful off course), actually I really like the opportunity to quickly show the related engine parameters (Template and Icon URI) before install like 'Selected search' add-on

Another user was looking for better integration with mycroftproject here #339. I'll use that thread to track changes. I'm not completely sure what can be done due to CORS, but I'll see.

> an icon in Tools for 'Search inside site' (subdomain\entire domain)

Would it need to be in Tools? Domain searches are already supported through search engines and are completely customizable (google/bing/ddg/etc). Check the readme for {domain}, {subdomain}, {selectdomain} as URL params ( pretty sure it's mentioned. If not, I'll give you more details here )

> boxes to tick (unselect after searching) in text view for multitabs search again with icon in Tools ('multitabs search for selected engines')

Can you elaborate on this one? I don't follow.

> double right click search option using default Firefox search engine (or latest used engine in ContextSearch) without using Quick Menu

Are you wanting a dedicated mouse action for triggering a search using the last-used engine (or the first engine in a new session) and bypassing the menu? And having that action bound to right double-click? So what would the action look like? Highlight a word, then simply double-click the right mouse and perform a search? 

I haven't even considered adding double-click actions to mouse options. I'm not certain how well they'd play with the current code. And as for double right-click, oh boy right-click is a PITA due to OS / browser differences in how the context menu is triggered ( mousedown vs mouseup ). Suppressing the default context menu has been a challenge. I'm not saying it can't be done, just that it very likely won't work for everyone on every platform.

Is this behavior something you've used in another addon?

**Comment by Github-PCDesktop** [comment]
Thank you for your answer.

1) Mycroft Project: I'll create a new post in  #339

2) Speaking about 'Search inside site' (or 'Reverse image search' too) you are right and I saw how the extension is organized. I like it despite probably I have take some time to deepen in it.  A picture is worth a thousand words so: 

<img src="https://i.postimg.cc/ZK6YbK66/Image-A.png">

Assumption: this is a 'optional' (and maybe useless) suggestion for 2050  release. I probably though about it after seeing 'Find bar' (very good work at the same level of dedicated extensions) and with one premise: there are dedicated extensions like 'Search site WE' and 'Search by image' with more options or\and a number of preset search engines (the point of view of a basic user). Depends on the goals. However, these options are secondary to the main purpose and I find your extension more practical than the others.

3) This is related to another simple but nice extension: 'Multi search engine'. I consider it the icing on the cake and not so necessary considered the option to 'Lock the menu'.

<img src="https://i.postimg.cc/wMXMNz4r/Image-B.png">

4) Well... I'm addicted to double click (open new tab, search, ...) despite the keyboard. Double left click to select and double right click to search! What I can say, when I have to use only the default search engine (most of the cases) I find it practical and fast. Always with dedicated extensions and in this case: https://addons.mozilla.org/it/firefox/addon/doubleclicksearch/.
Never a issue with 'ContextSearch' (or similar extensions) even with the option 'Left + Right click' (I use 'Hold + Left).
Unfortunately after Firefox Quantum the choices in this case are almost zero and this extension is set to work only with Google and not to default search engine. Moreover I tried for the first time ProtonVPN and it seem that VPN+Google=a little bit of Captcha.... I solved this with a redirect to another search engine using 'Privacy redirect'. So in detail I simply need a double right click after selection and if I understood well better with the first engine in a new session.

**Comment by dnknn** [comment]
> For Reverse image search, two professional tools are recommended here, I think they are both powerful.

- Search by Image　　	`.crx` extension
https://chrome.google.com/webstore/detail/cnojnbdhbhnkbcieeekonklommdnndci

- Search By Image　　`.js` UserJS
https://greasyfork.org/scripts/2998

------------------

<img align=right width=20% src=https://user-images.githubusercontent.com/10995302/122788757-3f87a800-d2e9-11eb-9551-66691ae3753f.png>

>Regarding the question you mentioned (please see the picture on the right)
This is not a problem, it is because you have not fully understood the full content usage of ContextSearch

```
chrome-extension://mlhlcahflgfgallicofkjfedfcgngkno/options.html#quickmenu
```

then, 👇	It has this function itself, it can meet your needs
![image](https://user-images.githubusercontent.com/10995302/122789310-c472c180-d2e9-11eb-8a49-224619a5fba7.png)

**Comment by Github-PCDesktop** [comment]
Sure, about point 3) I had suggested it at first glance before having deeply explored all the options. I posted the picture to explain but I redefinite the option as 'unecessary' and now I use Quick Menu with 'Lock Menu Open' and 'Open tab in background' together with latest your suggestion.
'Search by Image' is a very good and powerful extension but considered my needs now is more than enought 'Context Search' in order not to have duplicates. In the same way 'Search site' was a holy extension but Firefox Quantum has limited its integration inside search bar. 
I still have to manage through all settings however I believe that the suggested bars in the same way of 'Find bar' have the potential to overcome other dedicated extensions related to the search within the sites or about 'reverse images search' in particular if a user has sometimes need to focus on these searches. The foundations are there because 'ContextSearch' is well designed with the advantage that users are able to personalize search engines. 
Well, the title is 'optional suggestions' and maybe I'm wrong becasue I still to get use the extension. Anyways except for Mycroft Project feature request all works fine. 

PS: you reminded me Greasyfork! I forgot about it in order to find parameters for 'reverse image search' through scripts (I'm not a power user).

**Comment by dnknn** [comment]
I see you complaining 🦊Firefox, Maybe you can try to use Chrome/Chromium browser ^_^

because I think there is nothing wrong with Chrome/Chromium , Why not try it^_^

**Comment by Github-PCDesktop** [comment]
> 
> 
> I see you complaining fox_faceFirefox, Maybe you can try to use Chrome/Chromium browser ^_^
> 
> because I think there is nothing wrong with Chrome/Chromium , Why not try it^_^

I tried a couple of Chromium based browsers (obviously there isn't nothing wrong with them) but I got used to Firefox or its forks. Regarding 'Search site WE' I don't think it changes anything if I use Chrome, but it's a trivial complaint about an additional click to show the search bar. One browser is enough to loose time, I recently even uninstalled Edge.

**Comment by ssborbis** [comment]
@Github-PCDesktop 

If you're really wanting checkboxes for multisearches, I'll look into a left-mouse long-press causing checkboxes to appear. This is pretty standard behavior for a lot of lists I've seen in mobile apps.

**Comment by Github-PCDesktop** [comment]
Thanks, but you was right and it was my fault to have not really explored some options at the beginning. With the icon of 'Toolbar' and 'Keep Menu Open' in Quick Menu 'Search Action' checkboxes for multisearches become unecessary. However your idea about the left-mouse long-press causing checkboxes to appear could actually be useful, as you wrote, in a mobile context and touch mode (I suppose).

Since the first post (and I still have to manage through all settings) I can rewrite:

- double click right search with the first engine (totally optional, if it is possible and anyway there are already hotkeys I can get use or the dedicated extension)

<img src="https://i.postimg.cc/8kqdwGd5/Image-A.png">

- 'search site:' and 'reverse image search' bars (both totally optional).
I thought about these also because there is already the 'Find bar' as existing template and maybe there is less waste of time in coding about search engines parameters due to the extension folders design where users can add their personal engines (to be considered an advantage too). If I immagine some option like 'Save site for future site: search', 'Multitab site: search based on two o more words', or 'Upload txt with image ULR and do a reverse search with selested engine', no one dedicated extension can do this.

- 'open site instead search' in Quick Menu 'Search Action' options (totally optional and maybe it is already possible to do so)
I set many search engines and most of them are sites that I usually open (like news). Moreover I use a multi URL extension to group them and open at the same time instead of using bookmarks. I see in search engines settings the 'Form path' parameter (which always corresponds if I am not mistaken to the link of the site) that is set after 'Template' is inserted. Considered existing options and the folders organization this could be a little new option to use 'ContextSearch' as a quickly boomarks (single or group) opener.

<img src="https://i.postimg.cc/k4R6tVpy/Image-B.png">

Honestly speaking your extension it is already more than perfect this way and I uninstalled 4 extension after 'ContextSearch'. Except for 'Add custon search engine' (only regarding icons): there is something I still have to understand about icons URI: it seems resize my personal imported .ico icons or .pgn images or about .svg import file support. Not so important, but I prefer to use that extension for icons and than import the new search engine into 'ContextSearch'.

**Comment by dnknn** [comment]
@Github-PCDesktop Hi, Yes, there are indeed many people who did not go deep into various functions/options, and then made judgments/questions/suggestions, which I think is not good.

<img align=right src=https://user-images.githubusercontent.com/10995302/123325345-80daba80-d56a-11eb-9606-2b4455d1d488.png>

I will answer your question, Yes, It is an interactive indication of the first engine.
But do you know why this is the case ❓	
This is because it is used to indicate the `Enter` keyboard-key.
  - When the focus is on the search bar, 
  you pressing `Enter` will open it.

**Comment by Github-PCDesktop** [comment]
> 
> 
> But do you know why this is the case ❓

At least this time I already knew why ('there are already hotkeys'.... included 'Enter'), but I wasn't pretty sure when you wrote above 'first engine in a new session'.  However I have to admit that two days ago before use 'Enter' I clicked on the magnifying glass seeing a continue highlighting on the icon with the background that probably wanted to say me 'Use Enter', 'Use Enter', 'Use Enter'....  :-)
Although the use of mouse instead of keyboard is my personal preference (or problem), I still find more confortable use double right click when searching with the default search engine.  Totally optional.

**Comment by dnknn** [comment]
> Although the use of mouse instead of keyboard is my personal preference (or problem),

But you have to know a problem: 
`single-Right-Click` ⚔ `double-Right-Click` on an `element` at the same time, the logic is complicated, or it can be said to be a bit "conflict".
It is technically possible, but there will inevitably be problems?
Because the program needs to determine whether you are clicking or double-clicking, this requires additional function time calculations?

**Comment by dnknn** [comment]
> Although the use of mouse instead of keyboard is my personal preference (or problem),

But you have to know a problem: 
`single-Right-Click` ⚔ `double-Right-Click` on an `element` at the same time, the logic is complicated, or it can be said to be a bit "conflict".
It is technically possible, but there will inevitably be problems?
Because the program needs to determine whether you are clicking or double-clicking, this requires additional function time calculations?

-------------


However, I want to ask you a question: 👇

![216_25053531](https://user-images.githubusercontent.com/10995302/123335523-2ac04400-d577-11eb-8c64-3ef791f3f111.png)

 I have never understood the specific meaning of this tool icon, 
 because I tested `ON` or `OFF`, it is the same, I really don't understand its specific meaning.
 
 So I think the author should add a `title="...helpInfo.."` to the necessary html.

When the mouse `:hover` it, the help information of the tooltip will be displayed.

```html
							👇 tooltip 
<div class="toolIcon tool" title="tooltip for helpInfo" .... data-title="Instant Search" ....></div>

```

**Comment by Github-PCDesktop** [comment]
> 
> But you have to know a problem:
> `single-Right-Click` ⚔ `double-Right-Click` on an `element` at the same time, the logic is complicated, or it can be said to be a bit "conflict".
> 

Selfish optional suggestion. Maybe it is too difficult and If I remember well when I used another old 'double right click search' add-on (with Palemoon or Classic Waterfox) the browser right menu was being bypassed.

<img src="https://i.postimg.cc/dQZqK1nm/Double.gif">

I also experimented the 'Istant Search' icon. With my settings it immediately open the search after select and 'left hold' (useful). Maybe I'm wrong to find the right settings, but isn't 'Istant Search' based on last-used engine? A the same time I have to select or deselect this option otherwise it always performs a search even if I want use the Quick Menu for other engine. Right?

**Comment by ssborbis** [comment]
@Github-PCDesktop 

> open site instead search

If the search bar is empty, it will open the URL listed under Form Path. There is no dedicated action for this, however. 

I think you can open multiple engines as bookmarks if you place them in a folder, and use Search Actions -> Folders -> Open in Background Tab to launch all engines in that folder at once, provided the search bar is empty.

**Comment by Github-PCDesktop** [comment]
> 
> If the search bar is empty, it will open the URL listed under Form Path. There is no dedicated action for this, however.
> 

Sure, I already use right click from toolbar icon to do this.  If I'm not mistake, if the search bar is empty it will open the URL before the search parameter not the Form path. So it work well with most of the sites not all. 

https://arstechnica.com/search/?ie=UTF-8&q={searchTerms}
If the search bar is empty it will open: https://arstechnica.com/search/ 

https://www.scienzainrete.it/search/google/{searchTerms}#gsc.tab=0&gsc.q={searchTerms}&gsc.sort=
If the search bar is empty it will open:  https://www.scienzainrete.it/search/google/{searchTerms}

On the other hand, I was thinking about "Double Right Click Search" and 'the existing good option of 'Istant Search'.  A maybe not difficult and compatible compromise with the related icon enabled (if is not already possible to do so):
- the possibility to choose the engine to use (last search used engine or the first engine in the list)
- use 'Istant search' for example with hold+right button together with not use it with hold+left button (open the Quick Menu as always)
Even better than "Double Right Click Search" without using keyboard. And regarding the annoying captchas when using a VPN a solution could be a new 'VPN' icon in tools for:
- the ability to quickly use 'Istant search' with the 'second' search engine on the list
- or an automatically redirect only with Google in a similar way of 'Bypass-google-sorry-recaptcha' script or 'Privacy redirect' extension

Well, after this last idea nothing comes to mind anymore and as the title these are all 'optional' suggestions based on my  limited knowledge and personal behaviour performing searches or when a new engine needs to be added.  I hope I given you some helpful thoughts, but they are all small wishes already covered by other extensions or scripts. ContextSearch already works perfect without these.

**Comment by dnknn** [comment]
> [https://arstechnica.com/search/?ie=UTF-8&q={searchTerms}](https://arstechnica.com/search/?ie=UTF-8&q=%7BsearchTerms%7D)
> If the search bar is empty it will open: [arstechnica.com/search](https://arstechnica.com/search/)
> 
> [https://www.scienzainrete.it/search/google/{searchTerms}#gsc.tab=0&gsc.q={searchTerms}&gsc.sort=](https://www.scienzainrete.it/search/google/%7BsearchTerms%7D#gsc.tab=0&gsc.q=%7BsearchTerms%7D&gsc.sort=)
> If the search bar is empty it will open: [https://www.scienzainrete.it/search/google/{searchTerms}](https://www.scienzainrete.it/search/google/%7BsearchTerms%7D)

No... you are wrong, you can customize the URL to open when the searchbar is empty!

![image](https://user-images.githubusercontent.com/10995302/123553464-e10d6e80-d7ad-11eb-84f4-e5787c415464.png)

**Comment by Github-PCDesktop** [comment]
> This is a good feature💪, you should know it.

I know about what I see:

<img src="https://i.postimg.cc/L5f34jyP/Search.gif">


So I thought that it doesn't open the Form path (and then the suggestion).  But now I solved by deleting and saving the same default Forms paths. Maybe there's something I'm missing.

**Comment by Github-PCDesktop** [comment]
> Maybe there's something I'm missing.

Seems this happens only when you imported search engines from Firefox. I tried with a new profile using search.json.mozlz4 from my default profile.

**Comment by dnknn** [comment]
> > Maybe there's something I'm missing.

The version you are using is too old...![image](https://user-images.githubusercontent.com/10995302/123563527-cf48bd00-d7e7-11eb-8172-71be2e7e7348.png)

**Comment by ssborbis** [comment]
@Github-PCDesktop 

I'm not entirely sure what the discrepancy is between what @dnknn and I are seeing with the Form Path param and you're seeing. It may indeed be a matter of you using a version other than the latest, but I haven't checked. I don't recall any code changes between 1.28.1 and 1.30 that would account for the difference. There may be something else going on. In any case, the correct behavior should be to open the Form Path URL when searching with and empty search bar.

**Comment by Github-PCDesktop** [comment]
Now the latest official release is already 'too' old?  That's a little extreme.
The discrepancy is caused because you notice it with a very few engines (with more '/.../' before search parameters) and seems to relate when you import engines previously added with 'Add custom search engine' extension. Now I also tried 1.29beta1 with a new profile and following my previous steps:

- added 'Ars Technica with 'Add custom search engine'
  https://arstechnica.com/search/?ie=UTF-8&q={searchTerms}
- in 'ContextSearch' appeared 'Ars Technica' (FF locked). Empty bar search ---> ok
- imported the search engines, now 'Ars Technica' is unlocked. Empty bar search ---> arstechnica.com/search
- opened 'Ars Technica' settings, deleted the Form path and saved (again with the same Form path). Empty bar search ---> ok

This seem doesn't happen if you used 'ContextSearch' to add the engine and then try to delete and reimport it from Firefox.

<img src="https://i.postimg.cc/0j2f1fjy/Compare.png">

Doesn't matter, the solution is simple. For me you can close.

**Comment by ssborbis** [comment]
@Github-PCDesktop 

Capturing a double right-click on a webpage is proving quite difficult due to the system context menu being bound to that action. Do you have another example of a webextension using a right double-click and maintaining normal context menu behavior?

**Comment by Github-PCDesktop** [comment]
> Capturing a double right-click on a webpage is proving quite difficult due to the system context menu being bound to that action. Do you have another example of a webextension using a right double-click and maintaining normal context menu behavior.

No examples regarding search action, as a far I know, except for similar add-ons in Classic Firefox Archive. Seems there are some extensions which close tabs with double right click and there will probably be some too related to 'save'.
https://addons.mozilla.org/it/firefox/addon/close-tab-double-right-click/
https://addons.mozilla.org/it/firefox/addon/double-click-reload-and-close/
https://addons.mozilla.org/it/firefox/addon/rights-to-close-ex/
 
The only action that come close to double right click search is hold+right click with Istant Search enabled. It works well and already allows you to avoid the Firefox right menu, but actually it has a specific purpose (enabled or disabled, last used search engine).

**Comment by ssborbis** [comment]
@ghost

I'm doing some housekeeping on old issues and I'm wondering if you are still interested in a double-right-click function for searching, and if so, how exactly that should work. If you could, walk me through a brief example and I'll see what can be done.
