### ISSUE TITLE
Bug: CSS-Web-ext Context Menu will fail to generate on Mozilla Pages. (Will generate after making search in Toolbar Menu)

### ISSUE THREAD

**Issue by MintMain21** [ssborbis/ContextSearch-web-ext#384]
Basically, if I change the settings for ContextSearch-web-ext or install/updates a different add-on, the context menu option to search with ContextSearch may become hidden on Mozilla Pages until I highlight and right-click something on a normal webpage. After that, it's usable on Mozilla pages again.

It's a little difficult to track this one, but I know it happens frequently enough to be annoying when testing/searching multiple add-ons, and I can only assume that you are either already aware of it, or have already fixed it in a pre-build.

**Comment by MintMain21** [comment]
This bug got just a little worse. Now the context menu will be absent from any web page until I change another setting. Nothing game breaking, just kinda annoying.

**Comment by ssborbis** [comment]
Does it deactivate the entire context menu, or just the CS entry?

**Comment by MintMain21** [comment]
From my experience, the bug occurs most frequently when you manually check/install updates from the Firefox Add-On page (perhaps I should've mentioned I was using FF).

**Comment by MintMain21** [comment]
I think I finally solved it. All I had to do was change quickMenuAllowContextMenuNew in the advanced options. 

Gonna close, will reopen if necessary.

**Comment by MintMain21** [comment]
I don't understand it. It's clearly not being triggered by the manual updates anymore, at least not immediately. All I know for certain is that the context menu just will not generate on Mozilla pages until I make a search through the Toolbar. I suppose the Toolbar does offer a decent work-around, but it's annoying all the same.

**Comment by MintMain21** [comment]
Not gonna close it again yet, but I did find out that I had the Quick Menu enabled, but the ability to open the Quick Menu disabled. This may have been conflicting with the context menu, causing the bug. If I don't encounter it again within the next week, I'll close this for good.

**Comment by MintMain21** [comment]
Update: Before the context menu would only fail to generate on Mozilla pages, but I recently had one instance where it wouldn't load on a normal website (www.goodreads.com).

**Comment by ssborbis** [comment]
Have you checked the CS debug console? ( about:debugging -> ContextSearch -> Inspect ). It might have some useful info.

**Comment by MintMain21** [comment]
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 10 background.js:2455
The connection to wss://notifications.bitwarden.com/hub?access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkJDMzZDMjE0REI0OEYyMzVCNzdEQTNGMTcyMEMxQTM1QTk2MkVBNDNSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6InZEYkNGTnRJOGpXM2ZhUHhjZ3dhTmFsaTZrTSJ9.eyJuYmYiOjE2MzgzNDI4MTYsImV4cCI6MTYzODM0NjQxNiwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5iaXR3YXJkZW4uY29tIiwiY2xpZW50X2lkIjoiYnJvd3NlciIsInN1YiI6Ijk4MDEwNzYxLTUzYmUtNDg5MS1hZWQ3LWFjNjcwMDNmNTA0MSIsImF1dGhfdGltZSI6MTYwNTkyNzI4MSwiaWRwIjoiYml0d2FyZGVuIiwicHJlbWl1bSI6ZmFsc2UsImVtYWlsIjoibWljaGFlbGJlbGRAcHJvdG9ubWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInNzdGFtcCI6Ikg0M0FWSU1NNlFFT002TVRVVEc0REtSRkxFU01GTVBVIiwiZGV2aWNlIjoiZDIxOTMzMjctZDJjYy00ODkwLTkzMzItYjM5ZTEwMjI4MzFlIiwianRpIjoiOTFDNDA0N0VDQjZBNjYwNEE2MDE5NDNFMkUxQjhGRjMiLCJpYXQiOjE2MzgzNDI4MTYsInNjb3BlIjpbImFwaSIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJBcHBsaWNhdGlvbiJdfQ.QVr1ccRTZqLw7ELaVziWSzeMqyWZOyIUlCwYAbBWkR_zOU_cAOKf9Hy5ccsm0NLIDBBoZTZF6zGXtoBX-8UPyrURPPsa5VIW6EcVZzsclh5ShuRkf6tcCAaorTFX5DAv0IEQpXnDtI7erZWf6o0gtpAN071Q9qk2o_JfLM0PiuIgRe3y-I2sTjZCLKLOGT0GfZPO1TurHSPipecHdorEicA_8nSjjyBPdZCD8UVN-U28xLHW2d4DXjuUPjCL2GsZ8Rp6POMlLnZr3NHyQgjwnMgnJL2PSKcpOZ_y5IyVVDq9s7uPQxDKwsERnosDl9DLV7WDWlqJvFItdu0otEF4X6L8JZ8xyEkF2chtZWUIRpKE7cP-JghSxHx_FOGmzkVqxgDjmxZFsXevTC1_jB-se6wmgXYpaSPYP9IrkOown6d665m18a8_wgAhVwTdT0v5dTtCAEju7XJT4NDdJP6jff73SX8xU2wkkS8O8QfIBlEfQa2sbv8NTURE-a4D1TksgAFkg_8Oirc1pUalIE8B6E_OWOQGA49vldW5Ko1SWjNhP9eDVIxz_708S72UUm1kTwfEpjushNhUbzWBWfnYVLsO7bbL6JfGpRLVPrGc_O6HnKfrfYNbo5TkTq6VfBU2hHvfBTyuxx3DkXr3EX4R-68I1J-G85xhJVLg1koOn_M was interrupted while the page was loading. vendor.js:57614:44

**Comment by MintMain21** [comment]
Okay, so, on one computer I updated to version 1.31.9 (which in itself had an installation bug wherein I couldn't update the extension and instead had to uninstall and reinstall it), and it seems as if the "loads a blank tab when searching from Mozilla Page" bug is gone, but not the "fail to generate context menu" bug. I had to make a search from the toolbar in order to generate a context menu...... and then it's gone again and I have to search from the toolbar instead. 

Looking at the debug console like you suggested, it seems that there's a delay between the extension recognizing that the page is a mozilla page and employing the workaround to get the context menu to generate.

**Comment by MintMain21** [comment]
Okay, so the first computer I updated to 1.31.9 on was Windows, then I did Linux, and oddly enough the bug seems to be the other way around. The context menu WILL generate on Mozilla Pages, but search queries made via the context menu come up blank. At least, upon the initial attempts. And on Linux, it updated perfectly fine, no need to uninstall/reinstall.

**Comment by MintMain21** [comment]
Update on Linux: Context Menu works on Add-On page, search results go blank until/unless a search is made through the toolbar.

**Comment by ssborbis** [comment]
I've figured out how to reproduce the bug. I'm looking into it.

**Comment by ssborbis** [comment]
I'm kinda rolling this one into #403

The problem was, if the last searchTerms-changing action you performed on a non-restricted page was clearing the searchTerms ( deselecting text ), the menu would be disabled, until the next text selection ( via a context script ). Then, say, you went to a restricted tab / url, any text you select wouldn't register the new searchTerms, and thus would not rebuild the menu.

I've reworked the way content scripts are injected to hopefully detect this, and rebuild the menu accordingly. There will be a few bugs with the menu title.

I have also, as detailed in #403,  added an option to display the context menu differently, depending on the context using `contextMenuUseContextualLayout`. Enabling this, combined with new context checkboxes in the search engine edit modal, allows for only those engines with the proper context to be shown. If, for instance, you only have 3 engines with the `image` context ( reverse-image search engines, say ), only those 3 engines would be listed if you right-click on an image to open the browser context menu. There are some compromises with additional submenus to navigate when multiple contexts are detected ( image with link, etc ), but overall, I'd say it's a good addition. I also added an option `contextMenuContextualLayoutFlattenLimit` to flatten the menu ( no folders ) if only a few engines match the context. 

Test code is live in the dev repo, and I'll put up a signed pre-release soon.

**Comment by MintMain21** [comment]
Trying out 1.32a1 on Windows right now. So far so good. Will test on Linux soon enough. I'm very eager to close this issue for good, but I don't wanna end up eating my hat shortly thereafter. I'll do what I said I'll do before. If I don't encounter the bug again for a full week, I will close this and it's correlated issue for good.

**Comment by MintMain21** [comment]
Minor occurrence of the bug occurred on Linux. If I make a search from the Extensions page, then the context menu option will vanish while the new search tab is loading, but will reappear once the tab has finished loading. I emphasize that this is minor because it barely affects usability to the same level as it did before, and it resolves itself quite quickly. Only way this could hinder someone's workflow is if one wanted to make multiple searches of multiple phrases in quick succession. Testing this out on GitHub actually renders similar results, except the only menu option that will load for the extension is DDG, therefore the root of the issue isn't Mozilla Pages specifically. Again, barely affects usability and it could be the result of my laptop's weak CPU rather than the extension itself, but I felt it was worth reporting for posterity's sake.

Nevertheless, I will not count this as a re-occurrence of the originally reported bug, and if this is in fact the only remnant of the bug, I will close this issue in one week's time as promised.

**Comment by ssborbis** [comment]
Sounds good.

> If I make a search from the Extensions page, then the context menu option will vanish while the new search tab is loading, but will reappear once the tab has finished loading.

> Upon further inspection/reflect, this seems to be the result of my browser trying to summon more RAM/SWAP that isn't currently in use

The menu *is* rebuilt when:
1. a tab is activated ( received focus, etc )
2. the current tab is updated
3. the search terms have changed ( not actually rebuilt, but relabeled )

And because displaying the menu is an asynchronous action that can't be delayed while the addon menu build is incomplete, you may experience an incomplete menu if hardware resources are stressed.

Another consideration for Linux-type systems is, if the menu is displayed on mousedown vs mouseup, there's less time for the menu to update before being displayed ( the relabel action is on the mousedown event ).

The menus API is far from robust. I have no doubt there will be some lingering annoyances and I appreciate your help trying to clean things up.
