### ISSUE TITLE
Feature Suggestion: Recognize selected data string via regex and autosuggest search engines (skip nested folders)

### ISSUE THREAD

**Issue by robertheadley** [ssborbis/ContextSearch-web-ext#385]
I like, a lot of people have all of my search engines in nested folders. This is great for orginization but it can slow down the process. 

It would if we could set up categories based on regex validation, and then have preferred search engines for those categories. 

Examples
Persons Name : ^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$
IPv4 Address: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$

I took these from Dan's Tools so if that is not the right format of Dan's tools, I apologize. But I think this would add a lot of efficiency to ContextSearch web-ext

Either way, I always love the extension and the support you provide. Thank you.

**Comment by ssborbis** [comment]
I have some rough but functional code going. I'm appending a folder to the top of the menu containing engines with regex that matches the current search term.

![match_regex](https://user-images.githubusercontent.com/24310997/139567768-94ad10aa-3381-43a5-bc9f-97961b728a6c.png)

In the example, I made 4 engines with the regex `\d+`  ( well, "\\d+" actually ). Since the search term is a number, those engines are displayed first in a special group folder.

**Comment by ssborbis** [comment]
This feature has been improved since the last post. 

In addition, I'm including contextual options for engines as detailed in #403 which can also be used to show only relevant engines.

**Comment by robertheadley** [comment]
Great work.

**Comment by ssborbis** [comment]
If regex matching should be changed or expanded upon, please reopen or start a new issue. This feature was never fully fleshed out, so if you have some improvements in mind, let me know.
