### ISSUE TITLE
Firefox v95.0b11+ Popup Menu is not displayed correctly

### ISSUE THREAD

**Issue by wikiped** [ssborbis/ContextSearch-web-ext#392]
I have ContextSearch v1.31.2

I can't be sure if this is actually linked to Firefox itself (but I would presume so since I did not see any notification of ContextSearch update recently).

Since update to version 95.0b11 (and now b12) ContextSearch context menu is not displayed correctly. This is what it looks like instead of expected 2 rows by 8 columns grid with toolbar on top:

![ContextPopup](https://user-images.githubusercontent.com/5990528/143610065-c83c9385-3327-4d34-bf0f-08e4d1e7a41e.png)

While the settings are:

![SettingsPopup](https://user-images.githubusercontent.com/5990528/143610118-19b7311f-23db-447e-b2a9-6f04ae3237f8.png)

Thank you for the extension. Works great otherwise.

**Comment by ssborbis** [comment]
Thanks for the bug report. I think this is due to separators being included in the quick menu now. It looks like a separator is the 2nd element in your list. This would constitute a "row", so if you have one search engine followed by a separator, that would count as 2 rows, and the menu would shrink width-wise, since at that point it's only one column wide. If that sounds like your situation, try moving the separator around, or disable it. If not, report back.

**Comment by ssborbis** [comment]
added advanced option quickMenuHideSeparatorsInGrid under the advanced menu in v1.30.3

**Comment by wikiped** [comment]
Thanks. Separators were the culprits - I had to remove all of them to restore usual behavior.

It is still unclear why did it happen now? I had separators for as long as I have started to use the extension (months?) and there was no issue.

Thanks again.
