### ISSUE TITLE
Tabs with the search engines do open (they got the expected, correct name) although they appear to be blank

### ISSUE THREAD

**Issue by ssborbis** [ssborbis/ContextSearch-web-ext#410]
Hello again, importing the Waterfox config in question on a current Firefox profile leads to the following:
Tabs with the search engines do open (they got the expected, correct name) although they appear to be blank, stuck in a "loading" state for ages which also causes Firefox becoming unable to load **any** other page, it's like connections are being prevented by a firewall or internet access gets disabled or something. Then, after 2-3 mins or something, results finally come up and everything goes back to normal. This occurs both from context menu or tiles and it doesn't seem to make a difference whether it's a group of 3 engines or 10. What gives? Hope I don't have to recreate my entire config profile, search engines and all? Cheers!

_Originally posted by @Disappeaer in https://github.com/ssborbis/ContextSearch-web-ext/issues/304#issuecomment-994857645_

**Comment by ssborbis** [comment]
What versions of CS are you using?

**Comment by ssborbis** [comment]
@Disappeaer 

> I've noticed that if I've already got like, over 30-50 tabs or more (and I usually got much, much more) opened and I initiate a search in a group of more than 3 engines the browser really seems to struggle and stuck A LOT upon loading them up.

Does it only happen when doing a folder search ( multiple engines ) ?

**Comment by ssborbis** [comment]
I'm thinking it could be too many calls to update all tabs with the new config. Every time a search is performed, the config is updated and sent out to all tabs. If you have a ton open, that could cause a slowdown. I'm gonna add some debounce code to the 'update tabs' call. If you can test it out, we'll go from there.

**Comment by ssborbis** [comment]
I made an update to the dev repo fo you to try.

**Comment by Disappeaer** [comment]
> I've noticed that if I've already got like, over 30-50 tabs or more (and I usually got much, much more) opened and I initiate a search in a group of more than 3 engines the browser really seems to struggle and stuck A LOT upon loading them up.
> 
> Does it only happen when doing a folder search ( multiple engines ) 

Please notice the issue you've quoted from the **other** thread, the one I've mentioned today is not related with this one. That one is **Waterfox**-related that's why I talked about it **there.**In any case, yes it seems it can't handle loading up too many engine searches if there are already many tabs opened, searching using one search engine doesn't seem enough to cause this.
I was using 1.29 on Waterfox, I updated with the current repo code and the extension practically disappeared. No context menu, no tiles, not anything. I hope I'll be able to go back to 1.29.

As for the Firefox issue (the one I've mentioned earlier this week where you quoted me to create **this** very thread), I tried loading the same code as a temporary addon and it doesn't make a difference. Also, this issue occurs even when using a single search engine (IMDB) and not a whole folder only. The puzzling fact that it doesn't really crash the browser (or having it getting stuck) but I am unable to load any page (again, it's like I temporarily set my firewall to cut internet access on Firefox) and by giving the other users' issues a look (my tabs got a title instead of being completely blank, it's just nothing gets loaded until 2-3 mins pass),  leave me doubtful whether it's the same issue/bug they encountered.

**Comment by ssborbis** [comment]
I'm checking the latest code in Waterfox 2021.11 (64-bit). There does need to be some modifications to the context menu code to get it to work, but otherwise it loads fine for me. Quick menu works, toolbar menu, searches work.

**Comment by ssborbis** [comment]
Context menu fix is in the dev repo.

If that's still not fixing your issue, maybe you config got corrupted. I'll have to guide you through some debugging in that case.

**Comment by Disappeaer** [comment]
I really do think we should keep the two issues separate because it's confusing.
Let's use this thread for the Firefox Issue:
> Tabs with the search engines do open (they got the expected, correct name) although they appear to be blank, stuck in a "loading" state for ages which also causes Firefox becoming unable to load any other page, it's like connections are being prevented by a firewall or internet access gets disabled or something.

Trying the latest repo as a temporary addon (seeing there's no other way to load it on Firefox anyway) makes no difference.
Searches are initiated, I see the generated URLS, browser keeps loading and loading unable to load anything until 2-3 mins pass where everything goes back to normal. Btw, starting from a fresh config and adding 2-3 new search engines in a folder doesn't cause this issue. Which leads me to believe that just because it was a config created on Waterfox, it's not 100% compatible with Firefox causing the issue or something. Maybe it is corrupt indeed (which wouldn't explain why it works on Waterfox though).

**Comment by ssborbis** [comment]
> Which leads me to believe that just because it was a config created on Waterfox, it's not 100% compatible with Firefox

Can you send me that config?

Just so we're on the same page, you're getting code from the development branch, not the master / native-app-support branch, correct?

**Comment by Disappeaer** [comment]
> Just so we're on the same page, you're getting code from the development branch, not the master / native-app-support branch, correct?

Uuumm... No. I didn't even know that was a thing. I've probably mentioned before but github/dev stuff isn't really my forte... :)
However, I am happy to report that seemingly made the difference because making an .xpi with the code from the dev branch tackled the issues on both browsers! Maybe it's just the same issue then, manifesting itself in slight different ways?
Waterfox - things seemingly loading up but craaaawwliing / Firefox - tabs with the just the title open up instantly but getting the "internet down" firewall effect. So what was wrong and how did you manage to solve it? :)

Of course on Firefox I can just have it as a temp addon but I guess updating it on the Mozilla page wouldn't be a problem.

**Comment by ssborbis** [comment]
> I am happy to report that seemingly made the difference because making an .xpi with the code from the dev branch tackled the issues on both browsers!

Sweet!

> Of course on Firefox I can just have it as a temp addon but I guess updating it on the Mozilla page wouldn't be a problem.

I'll get a signed beta up in the release section now. I'm holding off a bit for a real release to AMO and chromestore. Look for 1.32.5a in the releases

**Comment by ssborbis** [comment]
1.32.6 live on AMO and Chrome store
