### ISSUE TITLE
"Highlight search terms" not working on https://www.startpage.com/

### ISSUE THREAD

**Issue by CrazieIvan** [ssborbis/ContextSearch-web-ext#446]
https://www.startpage.com/
The results are never highlighted for me.  

Also, on DuckDuckGo most results are highlighted but not all.  Only on google all the results are highlighted.

**Comment by ssborbis** [comment]
The DuckDuckGo issue might be due to dynamically loaded content after the highlighting script runs, but startpage works fine for me. Maybe we're using different templates?
![startpage](https://user-images.githubusercontent.com/24310997/150941519-b2a90e44-3e46-4d40-bd86-59f9c07b0adb.jpg)

**Comment by ssborbis** [comment]
After another look at DuckDuckGo, I think it's because they do their own type of highlighting on search results that wraps separate terms in bold syntax. You can try enabling `Highlight each word in multi-word search separately. Disable to treat phrases as a single search term` for search results. Seems to work for me.

**Comment by ssborbis** [comment]
DDG is working for me the same way with those settings. The URLs aren't being styled. I'm pretty sure it's a CSS specificity issue any there may not be a good fix, but I'll look.

Google looks good.

Yeah, Startpage is totally missing the styles in your pic, which is weird because I have no issues. Here's my full POST params for what it's worth

`query={searchTerms}&lui=english&language=english&cat=web&sc=hlctJPjkNuCB10&abp=-1`

**Comment by ssborbis** [comment]
Oh, and you may try enabling one or both of the following settings

```
Continue highlighting pages on the search results website
Continue highlighting on external websites linked from the search results page
```

It may be an issue where the results page isn't actually the final results page. If Startpage is referring you to a slightly different web address, you may need option 1 enabled to continue the highlighting on the subsequent page.

**Comment by ssborbis** [comment]
> It may be an issue where the results page isn't actually the final results page. If Startpage is referring you to a slightly different web address, you may need option 1 enabled to continue the highlighting on the subsequent page.

Yep, I just tested with `Continue highlighting pages on the search results website` disabled, and the highlighting wasn't there. Enable that, and you're good to go.

**Comment by CrazieIvan** [comment]
Good catch!!  Startpage works now. :-)
DDG works well enough.  I only mentioned it as a 'FYI', since I was already posting about Startpage.  It's no big deal.  

Thank you for the quick help!  You're awesome!

**Comment by ssborbis** [comment]
No prob
