### ISSUE TITLE
ebay campaign code?

### ISSUE THREAD

**Issue by atomGit** [ssborbis/ContextSearch-web-ext#532]
what's the purpose of this code...

```js
.then(_uo => {
    // remove campaign ID from ebay template ( mozilla request )
    let index = _uo.searchEngines.findIndex(se => se.query_string === "https://rover.ebay.com/rover/1/711-53200-19255-0/1?ff3=4&toolid=20004&campid=5338192028&customid=&mpre=https://www.ebay.com/sch/{searchTerms}");
    if (index === -1) return _uo;
    console.log("-> 1.14");
    _uo.searchEngines[index].query_string = "https://www.ebay.com/sch/i.html?_nkw={searchTerms}";
    return _uo;
})
```

**Comment by ssborbis** [comment]
I originally took the template url for the eBay search engine bundled with this addon from the Firefox search bar. Mozilla contacted me, asking to remove their unique identifier from my bundled search engine, because it was throwing off their analytics. I didn't even realize that's what it was, or I wouldn't have used it to begin with.
