### ISSUE TITLE
Partially exclude search results

### ISSUE THREAD

**Issue by Parvares** [ssborbis/ContextSearch-web-ext#583]
Hi Mike, could you help me? I'm trying to use your extension with this query: 

https://www.bibliotechediroma.it/opac/query/MAT:DVD%20%s?bib=RMBO2&context=tdoccd

(_MAT:DVD_ is the tipology of resourse, _RMBO2_ stands for Library-Biblioteca  and _tdoccd_ stands for audiovisual)

If I search by genre with the term "avventura" (i.e. "adventure"), like this:

https://www.bibliotechediroma.it/opac/query/MAT:DVD%20avventura?bib=RMBO2&context=tdoccd

I would have 141 results, but they are more than the they should, so I would like to find only the results that always have the search term  ("avventura") in the **tab "Lo trovi in" > Biblioteca Morante > Collocazione: [...] AVVENTURA [...]**

as in this case, for example: 

https://www.bibliotechediroma.it/opac/resource/i-goonies/RMB0442732

so have to be excluded the results that are only in the tab "scheda" or in the above abstract, but not in the tab "Lo trovi in", as in this case:

https://www.bibliotechediroma.it/opac/resource/avventura-tra-i-ghiacci-videoregistrazione/RMB0456526

Thanks very much, your assistance would be much appreciated!

**Comment by ssborbis** [comment]
Let me see If I understand you correctly.

You are searching for a *genre* but are also getting results where the *genre* appears in the title, and want to exclude those results? Or do I have that backwards?

**Comment by Parvares** [comment]
Yep, exactly, I would like to exclude search results coming from the title, the abstract and in general all the page related to tab “Scheda”, while I would like to get only search results with the “search term” placed in the tab “Lo trovi in” > "Collocazione... ", as in te screenshot I’m attacching… 


![Desired search results](https://user-images.githubusercontent.com/55709458/195012643-f2eb05f7-5db2-474b-94f3-64731496312e.jpg)

**Comment by ssborbis** [comment]
There's an advanced search button on that page that allows you to exclude terms from a number of categories. You could use those filters to exclude results that include the search terms in, for instance, the title. Of course, any result that matched the genre, but also included the search term in the title ( Adventures in Babysitting for example ) would be excluded.

A more thorough, but complicated method would be to use a web scraping tool. You could use the external application launcher feature + CS native app to send your search terms to the scraper. Although, I don't know what you're doing with the results.

Since the genre listed under `Scheda` doesn't seem to be knowable until you open each individual result URL, you'd need to collect the URLs of every result, open each link, and look for the searched-for *genre* in the genre section.

**Comment by Parvares** [comment]
I had tried the advanced search excluding search term in the title, but it has to be combined with a full search ("ricerca libera") to get the results from tab "Lo trovi in", and this combination would be contradictory and doesn't work... As for the other procedure 
unfortunately it would not simplify the search, since I need a single search... I hoped it was easier to reach the goal, thanks very much anyway!

**Comment by ssborbis** [comment]
> As for the other procedure unfortunately it would not simplify the search, since I need a single search... I hoped it was easier to reach the goal, thanks very much anyway!

It would be a single search. You just need to write a script to do the work.

**Comment by Parvares** [comment]
Ok, but I was aiming to reach a fast single list with a single search... :-(
