### ISSUE TITLE
Organize search engines list

### ISSUE THREAD

**Issue by MeX000** [ssborbis/ContextSearch-web-ext#6]
Search engines list shown in context menu is not sorted like in firefox options.
Attached two screenshots to make it clear.
![in_options](https://user-images.githubusercontent.com/12931005/34194474-59adaeea-e572-11e7-883c-ec89466327ff.PNG)
![in_context_menu](https://user-images.githubusercontent.com/12931005/34194481-5e86055c-e572-11e7-8935-4605d1b6f088.png)

Would be nice to be able to sort them (and add separators)

**Comment by ssborbis** [comment]
Hmm... it should sort them in the same order as the Firefox list.  Did you reload the search engines file after sorting?

**Comment by MeX000** [comment]
Sorry, my bad. After reloading sorting is as it should be.
Would be nice to have separators though.
Anyway, thanks for quick reply.

**Comment by ssborbis** [comment]
No problem.  I hesitate to add anything that isn't available to the Firefox search engines options because it would require maintaining a separate list.  And since the file has to be reloaded every time a change is made to the search engines list, it might get a bit messy; the nerfed FF57+ api is a bit of a pain like that.  I'll look into it though
