### ISSUE TITLE
Extension has been removed from addons.mozilla

### ISSUE THREAD

**Issue by peppersgc** [ssborbis/ContextSearch-web-ext#639]
Had to do a clean install of Firefox yesterday, and noticed that ContextSearch has been removed from the Firefox addons site. It is still up in the Chrome Web Store.

**Comment by ssborbis** [comment]
It's currently under review, and the reviewers are really taking their time. The "problem" is the libraries I'm using have been minified. Specifically, **https://github.com/mozilla/webextension-polyfill**

It's kinda ridiculous, because the official mozilla git gives this link https://unpkg.com/webextension-polyfill@0.10.0/dist/  but the addon was flagged  because unpkg.com is not considered a reliable source. I'm not too happy with the review process atm.

**Comment by ssborbis** [comment]
Placing a new release here. Still waiting on Mozilla

https://github.com/ssborbis/ContextSearch-web-ext/releases/tag/v1.46.10

**Comment by ssborbis** [comment]
1.46.9 is live now on mozilla
