### ISSUE TITLE
Version 1.46.18, not working properly

### ISSUE THREAD

**Issue by LengChenYang** [ssborbis/ContextSearch-web-ext#662]
After upgrading to the new version 1.46.18, the local cmd cannot be called by right-clicking. Switching to the old version works fine

**Comment by ssborbis** [comment]
Could you elaborate? Which "local cmd" do you mean?

**Comment by ssborbis** [comment]
also, what browser are you on?

**Comment by LengChenYang** [comment]
> Could you elaborate? Which "local cmd" do you mean?

It can be said that it is not possible to "Launching External Applications" in the web interface

**Comment by LengChenYang** [comment]
> also, what browser are you on?

edge and chrome

**Comment by LengChenYang** [comment]
> also, what browser are you on?

chrome 117.0.5938.132

**Comment by ssborbis** [comment]
I'm looking into this. I'll keep you posted with any updates.

**Comment by LengChenYang** [comment]
> 我正在调查此事。如有任何更新，我会及时通知您。

Looking forward to resolving the bug earlier

**Comment by ssborbis** [comment]
A few questions:

1. what happens when you try to use that yt-dlp launcher? Nothing?
2. which menu are you using when you open yt-dlp?
3. what is the current open tab? Is it a real webpage or a new tab page?
4. which version of the messenger app are you using? This can be found on the bottom left of any app launcher edit form
![image](https://github.com/ssborbis/ContextSearch-web-ext/assets/24310997/e60653bf-7401-4fea-8c45-591166504473)

Thank you for helping debug

**Comment by ssborbis** [comment]
1.46.20 going up with some fixes. Let me know if you can launch apps now

**Comment by LengChenYang** [comment]
> 1.46.20 going up with some fixes. Let me know if you can launch apps now

Thank you very much, the bug has not been reproduced
