### ISSUE TITLE
There have a bug on the chrome version 68(windows 10)

### ISSUE THREAD

**Issue by jerryawe** [ssborbis/ContextSearch-web-ext#88]
When I set it up,the option "Close After Search" don't work. ContextSearch-web-ext always close after first search.

**Comment by ssborbis** [comment]
How are you performing a search? Mouse click on a search engine? I'm not able to reproduce the bug. 

What platform?
Opening method?
Mouse button & setting?

**Comment by ssborbis** [comment]
Wait, do you mean the Quick Menu or the Toolbar search? I tested with both on chrome and they work as expected.

If it's the toolbar search you're having issues with, you need to click using a mouse button set to open a background tab. If you have your Left Mouse set to 'Open in New Tab', clicking a search engine in the Toolbar search will immediately open a new tab, causing the Toolbar search to close. This is because the Toolbar automatically closes any time it loses focus (nothing I can do about that).

**Comment by jerryawe** [comment]
According to your explanation, success,thank you very much.
I have a new problem，Some URLs cannot be added to template，such as
http://weixin.sogou.com/weixin?query={searchTerms}
https://www.google.com/search?q=site:www.cnn.com/%20{searchTerms}

**Comment by ssborbis** [comment]
`http://weixin.sogou.com/weixin?query={searchTerms}` added fine for me from the search engine manager. Query seems good too. What issues are you having?

------------------------------

`https://www.google.com/search?q=site:www.cnn.com/%20{searchTerms}`

should be 

`https://www.google.com/search?q=site%3Acnn.com+{searchTerms}`

If you want to use site search on the domain you're currently on, use 

`https://www.google.com/search?q=site%3A{domain}+{searchTerms}`

or 

`https://www.google.com/search?q=site%3A{subdomain}+{searchTerms}`

which is included in fresh installs of ContextSearch.

**Comment by ssborbis** [comment]
weixin.sogou.com also seems to add fine using the Add Custom Search option. Out of curiosity, is there a reason you're adding engines by hand vs using the context menu option?
